pool:
  vmImage: 'ubuntu-16.04'

resources:
- repo: self
  clean: true

jobs:
- job: Default
  timeoutInMinutes: 180
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - checkout: self
    clean: true
  
  - task: Docker@2
    displayName: login on docker hub
    inputs:
      command: login
      containerRegistry: docker-hub-gigi81
  
  - task: Docker@2
    displayName: image build
    inputs:
      command: build
      repository: gigi81/azurecross
      dockerfile: Dockerfile
      tags: x86_64-w64-mingw32
  
  - task: Docker@2
    displayName: Publish Docker Images to Docker Hub
    inputs:
      command: push
      repository: gigi81/azurecross
      tags: x86_64-w64-mingw32